google_domain_name = "indianagulu.com"
google_project_name = "My First Project"
google_project_id = "valued-clarity-288316"
google_bucket_name = "fuchicorp-blue-bucket"
deployment_environment = "qa"
credentials = "common-service-account.json"
deployment_name = "hello-world"